version: "3"
services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    network_mode: host

#  lambda:
#    image: lambci/lambda:provided.al2
#    volumes: 
#      - ./build/output:/var/task
#    command: todos
#    environment:
#      DOCKER_LAMBDA_STAY_OPEN: 1
#      AWS_LAMBDA_FUNCTION_MEMORY_SIZE: 128
#      DOCKER_LAMBDA_DEBUG: 1
#      DB_HOST: db
#    ports:
#      - "9001:9001"
#    mem_limit: 128
