name:                haskell-todos
version:             0.1.0.0
github:              "kbertalan/haskell-todos"
license:             BSD3
author:              "Bertalan Kis"
maintainer:          "kbertalan@gmail.com"
copyright:           "2021 Bertalan Kis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A sample web application in Haskell
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kbertalan/haskell-todos#readme>

dependencies:
- base >= 4.7 && < 5
- hasql
- hasql-migration
- hasql-transaction
- text
- http-types
- aeson
- mtl
- uuid
- vector
- unordered-containers
- wai
- bytestring
- random
- MonadRandom
- co-log
- chronos
- file-embed
- servant-server
- servant-errors
- servant-swagger
- servant-swagger-ui-redoc
- swagger2
- warp
- QuickCheck
- quickcheck-instances
- deepseq
- unliftio
- unliftio-pool
- prometheus
- prometheus-wai-middleware

ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fwrite-ide-info
  - -hiedir=.hie

default-extensions:
  - OverloadedStrings
  - BangPatterns
  - LambdaCase
  - NamedFieldPuns
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - StandaloneDeriving
  - FlexibleContexts
  - FlexibleInstances

library:
  source-dirs: src

executables:
  haskell-todos-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
    dependencies:
    - haskell-todos
    - optparse-applicative

tests:
  haskell-todos-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
    dependencies:
    - haskell-todos
    - hspec

